package sbnz.integracija;

import com.example.EuroTraveler.facts.Request
import com.example.EuroTraveler.facts.Response
import com.example.EuroTraveler.facts.Enums.Budget

rule "Budget LOW"
    when
        $req: Request ( budget/ageCategory.size() < 200, newStatus : Budget.LOW )
        $res: Response( )
    then
        modify($res){setBudget(newStatus)}
end

rule "Budget LOW_MEDIUM"
    when
        $req: Request ( budget/ageCategory.size() < 400 && budget/ageCategory.size() >= 200, newStatus : Budget.LOW_MEDIUM )
        $res: Response( )
    then
        modify($res){setBudget(newStatus)}
end

rule "Budget MEDIUM"
    when
        $req: Request ( budget/ageCategory.size() < 600 && budget/ageCategory.size() >= 400, newStatus : Budget.MEDIUM )
        $res: Response( )
    then
        modify($res){setBudget(newStatus)}
end

rule "Budget MEDIUM_HIGH"
    when
        $req: Request ( budget/ageCategory.size() < 800 && budget/ageCategory.size() >= 600, newStatus : Budget.MEDIUM_HIGH )
        $res: Response( )
    then
        modify($res){setBudget(newStatus)}
end

rule "Budget HIGH"
    when
        $req: Request ( budget/ageCategory.size() < 1000 && budget/ageCategory.size() >= 800, newStatus : Budget.HIGH )
        $res: Response( )
    then
        modify($res){setBudget(newStatus)}
end

rule "Budget LUXURY"
    when
        $req: Request ( budget/ageCategory.size() >= 1000, newStatus : Budget.LUXURY )
        $res: Response( )
    then
        modify($res){setBudget(newStatus)}
end